### ISSUE TITLE
how to add new events to `data/events.json`?

### ISSUE THREAD

**Issue by bbinet** [gre/jardin#2]
As a gardener and computer guy, I'm also very interested by your project to manage my own garden.

I see that everything that build your garden is centralized in the `data/events.json` file. That is great and I was wondering if you were editing the `data/events.json` file by hand or if you had another tool to ease the process of adding new events to that file?

**Comment by gre** [comment]
thanks for looking up in this project.

yeah, I'm editing it by hand. the app is just read only reading that file that I maintain by hand. And there is tons of things I want to do on just making this readonly (visualizing things in a cooler way (I want to inspire from things like pixelart & games :D), suggesting things to do, analysing more things...).

Disclaimer: The app itself is likely to still contain some specifics to my own garden and things might not all generalized in that data/events.json (and there might be some French & things specific to my climate (in data/families.json)). I'm currently doing it for myself only, I need to reach more interesting features before considering generalizing things. So basically, feel free to fork this if you want but don't expect a generalized solution out of the box yet;

**Comment by bbinet** [comment]
Thanks, for your answer.
I'm also from France (Chambéry), so your data should be quite good for me too!

I'll try to use it for my garden this year and see if it works enough for me.

**Comment by gre** [comment]
the important part in my mind is to try to log as much things as possible. I'm still likely to change/enrich the event format, but the point is to have data for later :)
e.g. the 3 year, you want to know what vegs you used to have so you don't replant same at same place (culture rotation) :D

**Comment by gre** [comment]
Ideally I also want to try to automatize the data feeding process, like the level of water in tanks. the temperatures over times, etc.etc.etc. :D
I plan to eventually do some arduino/raspberry, but it's getting tricky hehe.

I think what I want eventually is my app to warn me when I do things wrong or I miss something. for instance, I just had a problem in my current seedlings, I let my cuncumber seedlings too much burn in the sun, forgot to open the greenhouse :'( if I had something to watch temporature, it would have fixed it :D (or eventually if this can be automated XD)

**Comment by gre** [comment]
it's a whole experiment and I don't know exactly where I'm going. but I'll see over time what data I missed to log and where I was too overkill and could ignore data based on direction I go.

**Comment by bbinet** [comment]
Sure, gathering data is the most important thing. Then the tools to use and display the data can easily be improved in the long run.

Note that I really like all the data you've imported in the `data/families.json` file. That is very useful, thanks.

**Comment by bbinet** [comment]
Do you think you could provide and maintain a [jsonschema](https://jsonschema.net/) document for the `data/events.json` file, so that we can use a tool like https://github.com/mozilla-services/react-jsonschema-form to generate a form to update the `data/events.json` file?

**Comment by gre** [comment]
interesting idea for sure!

the data/events.json are not yet stable.. need more thoughts and maturation .. I'm still in the process of simplifying the number of events you need to log VS what data i really need.

for instance i'm probably going to get rid of the "add-seedlings" idea.. i don't care the app to track where my seedlings are.. but only to care what i have done, how much.. ( i'll still track where they are on the garden tho, but not where they are in the greenhouse )

I have hard time figuring out what nice format for the "plot" (the garden you have, where plant you have planted where). I have started to represented as a grid. it works nicely for seeds you throw ("surface seedling") but it does not work much for big plant you plant at exact position. so i need probably to allow both and figure out a nice format.
